### ISSUE TITLE
Problem with error logging

### ISSUE THREAD

**Issue by jurgenhaas** [crowdsecurity/php-capi-client#21]
Since we've deployed the brand-new Drupal plugin now on live sites, we're seeing an issue with the way how the CAPI is doing error reporting. Here is one issue that we saw last night:

There is a sequence of 2 log entries that result from the same request. The first one is an error with the message `Unexpected response status code: 401. Body was: @"message":"The incoming token has expired"` and the type `WATCHER_CLIENT_FORMAT_RESPONSE`. The second one is a warning with the same message and the type `WATCHER_REQUEST_ERROR_401`.

This is happening in `\CrowdSec\CapiClient\Watcher::manageRequest` where the called request caused an exception that logged the error and the calling function is catching that exception and logging the same thing as a warning.

That's double reporting and should be avoided.

In addition to that, it seems that this is expected behaviour and the client is retrying to login. In such a case, this should not be reported as an error at all.

**Comment by julienloizelet** [comment]
Hi @jurgenhaas,
Thanks for your message.

I published a new `capi-client` release `0.9.0` with updated log behavior : 
- Use message parameter in logger instead of a context message field
- Do not log error on `formatResponseBody` to avoid double reporting 
- Log retries as `info` and not as `error` as it is expected behavior

Please see the full [release description](https://github.com/crowdsecurity/php-capi-client/releases/tag/v0.9.0) for other included modifications.


There is also a [remediation-engine release 0.5.0](https://github.com/crowdsecurity/php-remediation-engine/releases/tag/v0.5.0) including this update of `capi-client`.

Thanks
